var MSolrConst={CONFIG_COLLECTION_NAME:"msolr",SOLR_URL_KEY:"url",NS_KEY:"ns",COLL_FIELD_KEY:"f",LAST_TIMESTAMP_KEY:"ts"},MSolrServer=function(a,c){this.configColl=a;this.configDB=a.getDB();this.loc=c};MSolrServer.prototype.index=function(a,c,b){a.indexOf(".")==-1?this._indexByDB(a,b):this._indexByNS(a,c,b)};MSolrServer.prototype.remove=function(a,c,b){a.indexOf(".")==-1?this._removeByDB(a,b):this._removeByNS(a,c,b)};
MSolrServer.prototype._indexByDB=function(a,c){for(var b=this.configColl.getMongo().getDB(a).getCollectionNames(),d=c||!1,f,e=b.length;e--;)f=b[e],/^system\..*/.test(f)||this._indexByNS(a+"."+b[e],null);d&&this.configDB.getLastError()};MSolrServer.prototype._removeByDB=function(a,c){var b={},d=c||!1;b[MSolrConst.SOLR_URL_KEY]=this.loc;b[MSolrConst.NS_KEY]=RegExp("^"+a+"\\..+");this.configColl.remove(b);d&&this.configDB.getLastError()};
MSolrServer.prototype._indexByNS=function(a,c,b){var b=b||!1,d={},f={},e={};e[MSolrConst.SOLR_URL_KEY]=this.loc;e[MSolrConst.NS_KEY]=a;if(c!=null)f[c]=MSolrDb.INDEX_COLL_FIELD_OPT,d[MSolrConst.COLL_FIELD_KEY]=f;this.configColl.update(e,{$set:d},!0);b&&this.configDB.getLastError()};MSolrServer.prototype._removeByNS=function(a,c){var b={},d=c||!1;b[MSolrConst.SOLR_URL_KEY]=this.loc;b[MSolrConst.NS_KEY]=a;this.configColl.remove(b);d&&this.configDB.getLastError()};MSolrServer.prototype.toString=function(){return this.loc};
MSolrServer.prototype.tojson=function(){return this.toString()};var MSolr=function(a,c){var b=db.getMongo(),d=a||MSolr.getConfigDBName(b),f=c||MSolrConst.CONFIG_COLLECTION_NAME,e={};this.db=b.getDB(d);this.coll=this.db.getCollection(f);e[MSolrConst.SOLR_URL_KEY]=1;e[MSolrConst.NS_KEY]=1;this.coll.ensureIndex(e,{unique:!0})};MSolr.getConfigDBName=function(a){for(var c=!1,b="config",a=a.getDBs().databases,d=a.length;d--;)if(a[d].name=="config"){c=!0;break}c||(b="local");return b};
MSolr.prototype.showConfig=function(){return this.coll.find()};MSolr.prototype.changeUrl=function(a,c,b){var d={},f={},b=b||!1;d[MSolrConst.SOLR_URL_KEY]=a;f[MSolrConst.SOLR_URL_KEY]=c;this.coll.update(d,{$set:f});b&&this.db.getLastError()};MSolr.prototype.removeServer=function(a,c){var b={},d=c||!1;b[MSolrConst.SOLR_URL_KEY]=a;this.coll.remove(b);d&&this.db.getLastError()};MSolr.prototype.server=function(a){return new MSolrServer(this.coll,a)};
MSolr.prototype.index=function(a,c,b,d){b==null?this.server(a).index(c):this.server(a).index(c+"."+b,d)};MSolr.prototype.toString=function(){return"config_collection: "+this.coll.getFullName()};MSolr.prototype.tojson=function(){return this.toString()};MSolr.prototype._getConfigColl=function(){return this.coll};MSolr.prototype.reset=function(){return this.coll.remove()};MSolr.DEFAULT=new MSolr;MSolr.showConfig=function(){return MSolr.DEFAULT.showConfig()};MSolr.reset=function(){return MSolr.DEFAULT.reset()};MSolr.SERVER=null;MSolr.connect=function(a){a==null&&(a="http://localhost:8983/solr");MSolr.SERVER=a};MSolr._checkConnection=function(){if(MSolr.SERVER==null)throw"Not connected to any Solr Server.";};DB.prototype.solrIndex=function(){MSolr._checkConnection();MSolr.DEFAULT.index(MSolr.SERVER,this.getName())};DB.prototype.dropSolrIndexes=function(){MSolr._checkConnection();MSolr.DEFAULT.server(MSolr.SERVER).remove(this.getName())};
DB.prototype.getSolrIndexes=function(){var a={},c=RegExp("^"+this.getName()+"\\..+");MSolr._checkConnection();a[MSolrConst.SOLR_URL_KEY]=MSolr.SERVER;a[MSolrConst.NS_KEY]=c;return MSolr.DEFAULT._getConfigColl().find(a)};(function(){var a=DB.prototype.help;DB.prototype.help=function(){a.apply(this);print("\tdb.solrIndex() - sets all collections under this db for Solr indexing");print("\tdb.getSolrIndexes() - shows the Solr indexing configuration for this db");print("\tdb.dropSolrIndex() - removes all collections under this db from Solr indexing")}})();
DBCollection.prototype.solrIndex=function(a){MSolr._checkConnection();MSolr.DEFAULT.index(MSolr.SERVER,this.getFullName(),a)};DBCollection.prototype.getSolrIndexes=function(){var a=this.getFullName(),c={};MSolr._checkConnection();c[MSolrConst.SOLR_URL_KEY]=MSolr.SERVER;c[MSolrConst.NS_KEY]=a;return MSolr.DEFAULT._getConfigColl().find(c)};DBCollection.prototype.dropSolrIndex=function(a){MSolr._checkConnection();MSolr.DEFAULT.server(MSolr.SERVER).remove(this.getFullName(),a)};
DBCollection.prototype.dropSolrIndexes=function(){this.dropSolrIndex()};(function(){var a=DBCollection.prototype.help;DBCollection.prototype.help=function(){a.apply(this);var c=this.getName();print("\tdb."+c+".solrIndex() - set this collection for Solr indexing");print("\tdb."+c+".getSolrIndexes() - show the Solr indexing configuration for this collection");print("\tdb."+c+".dropSolrIndex() - removes this collection from Solr indexing")}})();
